"""
Module: explain
SRS Reference: FR-NLP-001, FR-NLP-002, FR-NLP-003, FR-NLP-004, FR-NLP-005,
               FR-NLP-006, FR-NLP-007, FR-NLP-008, FR-NLP-009
SDLC Phase: Phase 3 — Sprint D (implementation begins Chain 08)
Sprint: D
Pipeline Stage: NLP
Interface Contract:
  Input:  label: str ("bonafide"|"spoof")
          confidence: float ∈ (0.0, 1.0)
          band_pct: dict[str, float] — 4-band attribution summing to 100.0
  Output: str — English explanation paragraph, 3–5 sentences [FR-NLP-001, FR-NLP-004]
                Non-empty guarantee: rule-based fallback always available [FR-NLP-003]
Latency Target: ≤ 8,000 ms (Qwen 2.5 API) | ≤ 100 ms (rule-based fallback) per NFR-Performance
Open Questions Resolved: Q1 — Qwen 2.5 (Alibaba Cloud) confirmed [FR-NLP-002]
Open Questions Blocking: None
MCP Tools Used: stitch-mcp (Qwen 2.5 async), context7-mcp (openai SDK)
AI Generated: true
Verified (V.E.R.I.F.Y.): false
Author: Ferel / Safa
Date: 2026-03-19
"""

# [DRAFT — Phase 3 — Sprint D — Pending V.E.R.I.F.Y.]
# Implementation: Chain 08 — Sprint D
# Security: API key MUST be read from os.environ[config.yaml:nlp.api_key_env_var] [FR-NLP-005]
#           NEVER log the key value — log the env var NAME only.

from __future__ import annotations

import os


_RULE_BASED_TEMPLATES: dict[str, str] = {
    "spoof": (
        "The audio sample has been classified as SPOOF with {confidence:.0%} confidence. "
        "The analysis detected artificial or synthesised speech characteristics. "
        "The model's attention was most concentrated in the {top_band} frequency band "
        "({top_band_pct:.1f}%), which is commonly associated with synthesis artefacts. "
        "This result suggests the audio may have been generated by a text-to-speech "
        "or voice conversion system."
    ),
    "bonafide": (
        "The audio sample has been classified as BONAFIDE with {confidence:.0%} confidence. "
        "The analysis identified natural human speech characteristics. "
        "The model's attention was most concentrated in the {top_band} frequency band "
        "({top_band_pct:.1f}%), consistent with natural vocal tract resonances. "
        "No significant artefacts of voice synthesis or conversion were detected."
    ),
}
"""Rule-based fallback templates. SRS: FR-NLP-003. Always available — zero external deps."""


async def generate_explanation(
    label: str,
    confidence: float,
    band_pct: dict[str, float],
) -> str:
    """Generate a natural-language explanation for a deepfake detection result.

    Fallback chain (SRS: FR-NLP-002, FR-NLP-007, FR-NLP-003):
        1. Qwen 2.5 via async API (timeout = config.yaml:nlp.timeout_sec = 30 s) [FR-NLP-002]
        2. Gemma-3 secondary fallback if Qwen times out or returns an error [FR-NLP-007]
        3. Rule-based template (_RULE_BASED_TEMPLATES) — zero deps, always available [FR-NLP-003]

    Caching (SRS: FR-NLP-008 — SHOULD):
        Cache key: (label, confidence_bucket, top_band)
        confidence_bucket: discretised per config.yaml:nlp.caching.confidence_buckets
        Cache is in-memory dict — reset on app restart. Not persisted to disk.

    Security:
        API key MUST be read from os.environ[config.yaml:nlp.api_key_env_var].
        NEVER log the key value. Structured log must show env var name only. [FR-NLP-005]
        If API key absent → skip tier 1 + tier 2, use rule-based fallback. [FR-NLP-003]

    Args:
        label (str): Prediction label. Must be "bonafide" or "spoof".
        confidence (float): Sigmoid output ∈ (0.0, 1.0). Passed verbatim to prompt.
        band_pct (dict[str, float]): 4-band attribution scores summing to 100.0 ± 0.01.
                                     Required keys: "low", "low_mid", "high_mid", "high".

    Returns:
        str: English explanation, 3–5 sentences. Non-empty — rule-based fallback guarantees
             a valid string even if all API calls fail.

    Raises:
        ValueError: if label not in {"bonafide", "spoof"}
        ValueError: if band_pct does not contain all 4 required keys

    Latency Target:
        ≤ 8,000 ms (Qwen 2.5 API time-to-first-byte) [NFR-Performance]
        ≤ 100 ms (rule-based fallback, no API call)
    """
    raise NotImplementedError(
        "generate_explanation() not implemented — stub only. "
        "Implement in Chain 08 (Sprint D)."
    )
